### PR TITLE
Switch from SumoLogic to Splunk

### PR DESCRIPTION
**Pull request by forabi**
Closes #453 #280

### CODE REVIEW

**Comment by forabi** [comment]
I'm going to test Splunk with an internal build.

**Comment by forabi** [comment]
Um, looks like HTTP collectors in Splunk Light enforce HTTPS but use a _self-signed_ SSL certificate, which Node.js refuses. I'll need to figure out how to work around this.

**Comment by forabi** [comment]
This is ready! Should I merge? Just a reminder that Splunk Light is in trial and our instance expires in 10 days.

**Review by wholesomedev — APPROVED** [review]
LGTM!

**Pull request merged**
