### PR TITLE
Get project to build with new Webpack config and start refactoring

### PR DESCRIPTION
**Pull request by forabi**
So as discussed in #111, #113, this PR introduces major changes to the build process and directory structure.

As this PR introduces lots of changes, I made sure to provide descriptive commit messages for each commit and also added extensive comments to `webpack.config.js` and most of the changed files, but here is a short summary of the changes:

1. Significantly improved build process for development and production: all of the changes discussed in #111 are incorporated and in addition Webpack is now configured with Hot Module Replacement (HMR) for development environments so code changes are immediately detected and you do not have to reload the page. Full details are described in the commit message for 8c5608c30a46713b8039eaabcefcb63f71bb18bf.
2. Update developer tooling: use [prettier](https://github.com/prettier/prettier) to automatically format JS, TS and CSS files. It is executed as a git hook before every commit. TSLint now uses [ts-config-pretterier](https://github.com/alexjoverm/tslint-config-prettier) so it does not conflict with prettier and does not complain about things prettier can fix automatically.
3. Restructure redux dir as discussed in #113.
4. Enable TS strict option, and fix a lot of issues in order to get the project to build.
5. Better type definitions for components wrapped in `connect()`.
6. Use `React.PureComponent` every where instead of `React.Component`. Pure components are more efficient and do not break any functionality.
6. Upgrade all dependencies to latest versions.

There are still some issues related to TSLint and the project won't build unless linting is disabled, which can be done with the new `NO_LINT` flag:

```
NO_LINT=1 yarn client/dev
```

Make sure to update dependencies before running the command.

### CODE REVIEW

**Review by wholesomedev — COMMENTED** [review]
Awesome work!

Just a few comments/questions:
* Why do we need to separate `react.js` and `vendor.js`?
* We don't need `stylelint` now, but I guess it'll come in handy if we switch to plain CSS in the future?
* We have a guideline of strictly not using JS anywhere, but I saw your explanation for why using JS makes sense for config files. In that case, can you please update the guidelines?

I'm okay with merging these changes. However, I see that there are some configurations and code that were added as preemptive measures. As a general approach, I would recommend that we start with the simplest code for our immediate needs and as our needs evolve, we can continue to redesign, refactor, and improve.

**Review by wholesomedev — DISMISSED** [review]

**Comment by wholesomedev** [comment]
The CI needs to be fixed :)

**Comment by forabi** [comment]
@msafih The reason for two separate chunks is that the vendor code may change more frequently compared to react libraries (react, react-dom, react-redux). So say if we bring in a new helper function from lodash, `react.js` won't change so the browser won't have to redownload this file again. It basically boils down to how frequently we expect vendor vs react code to change.

**Comment by forabi** [comment]
@msafih We are currently using some global css in `client/src/globalStyles.css` so that's why I added stylelint. Should I remove it?

**Comment by wholesomedev** [comment]
@forabi Ah, I see. No, I think it's fine to keep it. 

With the preemptive code I was mainly referring to some code in `env.js` like `isInferno` and some of those checks are used in `webpack.config.js` and they don't do anything as far as I could tell, like `isES5`.

Speaking of the variable name `isES5`, it doesn't comply with the naming guidelines we have. Could you fix that please?

**Comment by forabi** [comment]
@msafih I fixed two issues blocking CI but it is still failing as I still have to fix TS lint issues. I also fixed the inconsistent camel casing. It takes some getting used to 😅.

**Comment by wholesomedev** [comment]
Yeah, it doesn't always feel natural. It is more consistent though. 😄 

Once this passes the CI, we can merge it.

**Comment by forabi** [comment]
@msafih So all blocking issues are now resolved but the build is failing because of the enforced size limits on webpack assets. How would you like to handle that? Should I disable these limits by prefixing the build command with `NO_PERF_CHECKS=1`?

**Review by wholesomedev — APPROVED** [review]
LGTM

**Pull request merged**
