### PR TITLE
Attempt to fix different date strings by timezone in snapshots

### LINKED ISSUE #393: Jest tests fail when run on a machine with a different timezone?
When I run Jest on my local machine, I get the following error

image

### PR DESCRIPTION
**Pull request by forabi**
The date string returned from the API does not have any timezone info (because the original data didn't). We have to assume a specific timezone to get constant date strings across different timezones.

Closes #393

### CODE REVIEW

**Comment by forabi** [comment]
@wholesomedev Can you try this change and see if it fixes #393.

**Comment by wholesomedev** [comment]
I pulled `forabi:attempt-to-fix-date-timezone`, `rm -rf node_modules` (just for good measure), then `yarn install`, then `yarn test` but it still failed with the same date issue

**Comment by forabi** [comment]
Hmm, welcome to the JavaScript `Date` mess...

**Comment by wholesomedev** [comment]
@forabi Can we mock the date functions for the tests?

**Comment by forabi** [comment]
> @forabi Can we mock the date functions for the tests?

I don't like mocking in general, and I think setting a time zone on the date is a better solution. I just made some changes to this branch, can you try again now?

**Comment by forabi** [comment]
@wholesomedev The weird thing about this issue is that the tests pass both on my machine and on CI. They are definitely on different timezones. So why does it fail for you? Could it be because of different OSes?

**Comment by forabi** [comment]
> The weird thing about this issue is that the tests pass both on my machine and on CI. 

Well, it's not weird I guess, because CI and my machine could still be on the same day, even if the timezones are different.

**Comment by wholesomedev** [comment]
@forabi I pulled, `yarn install`, `yarn test`, still same issue.

It seems to be failing on the CI too now?

**Comment by forabi** [comment]
It's failing on CI because the bundle size increased.

**Comment by forabi** [comment]
I changed the timezone on my machine to match yours and I was able reproduce the issue.

The solution is very simple and elegant -- it turns out we can set the timezone for Jest with the `TZ` env variable:

```
TZ=UTC jest
```

That did the trick!

**Comment by forabi** [comment]
@wholesomedev Feel free to merge this after confirming it works for you. We should rebase #394 on master after merging this and revert the change to the snapshots.

**Comment by wholesomedev** [comment]
This works! 🎉

**Review by wholesomedev — APPROVED** [review]

**Pull request merged**
