### PR TITLE
Upgrade to config v10

### PR DESCRIPTION
**Pull request by forabi**

### CODE REVIEW

**Comment by forabi** [comment]
Looks like `yarn` will rewrite `package.json` to remove duplicate packages in "dependencies" and "devDependencies". Merging this will cause deployment to fail (same as #405).

**Comment by wholesomedev** [comment]
@forabi should we move `npm-run-all` to `dependencies` in `clown/common` for now?

**Comment by forabi** [comment]
@wholesomedev Never mind, I quickly looked at the diff and thought `npm-run-all` was removed from `dependencies`, but the entries were just re-sorted in `devDependencies`.

**Review by wholesomedev — COMMENTED** [review]
LGTM

**Pull request merged**
